### ISSUE TITLE
Make IR objects (immutable) hashable

### ISSUE THREAD

**Issue by dafrose** [pyrates-neuroscience/PyRates#2]
Making IR object immutable could produce a considerable performance boost, but also change a couple of interfaces. 

### Suggested changes
- [ ] `CircuitIR`, `NodeIR`, `EdgeIR, `OperatorGraph` and `OperatorIR` become (pseudo-)immutable, rather hashable. Changing something about them produces a new instance.
- [ ] IR objects implement custom `__hash__` methods.
  - hash is computed from hash of contained objects
  - hash is computed upon initialization
- [ ] IR objects implement `__eq__` method.
  - IR objects can be compared by simply using the `==` operator.
  - Equality is defined by same class and same hash. (Class could actually be part of the hash already.)
- [ ] Instead of copying IR objects from an object cache, identical objects could actually be references to the same object. 
  - Changes to cached objects might need to produce new cache entries.

### Advantages
- Simplifying syntax for comparing IR objects (a lot).
- Increase of performance in vectorization: Do not need to compare every little detail, just compare hash.
- Possibly simplify vectorization syntax a lot.
- Improve performance and memory usage of IR objects by referencing cached objects multiple times instead of copying.

### Disadvantages
- Changes API of IR layer (only the part that faces the backend, though)
- Either backend needs to be changed to allow for immutable IR objects - or IR objects need to be implemented in such a way, that they can be changed naturally by silently producing new objects. That may cost performance, though.
- Possibly loss of performance due to complicated hashing (although this is only done once per object).

### Edits: relaxed the immutability requirement to a hashable object that tries to prevent you from altering it.

**Comment by Richert** [comment]
Not required anymore, since IR objects are not accessible to the user anymore and hence cannot be changed by the user. Vectorization is already performed when templates are translated into their IR equivalents and thus wouldn't benefit from the change either.
