### ISSUE TITLE
Improving user friendliness and stability of PyRates

### ISSUE THREAD

**Issue by Richert** [pyrates-neuroscience/PyRates#21]
This is just a list of improvements that may be added to the user interface, documentation, testing suite etc.

Documentation
--------------------

- [x] FortranBackend
- [x] CircuitIR methods
- [x] readthedocs layout
- [x] readthedocs how-to section
- [ ] known bugs, problems and unsupported usage of PyRates

pytests
----------

- [x]  Tests for different types of edge delay conversions
- [x]  Tests for FortranBackend
- [x]  Tests for scipy solver
- [x]  Tests for multi-level circuit hierarchies
- [x]  Tests for new edge syntax in yaml files
- [x]  Tests for all methods on CircuitIR
- [x]  Tests for proper variable name translation into backend (including solving identical variable names) 

convenience features
-----------------------------

- [x]  variable setter method
- [x]  variable getter/setter methods that works with edge variables as well
- [x]  i/o methods for saving/loading different objects along the frontend-to-backend chain
- [x]  add more prints of ongoing processes to different stages of frontend-to-backend chain and make them mutable via verbose argument
- [x] add more model templates for different descriptions of neural population and synaptic dynamics

**Comment by dafrose** [comment]
add to that:
- [ ] templates and tests that use the pure Python interface instead of the YAML interface.

regarding the "more printing" task: I actually would like to suggest that we start using `logging`. That way we can distinguish better between `DEBUG`, `INFO` and `WARNING` messages and give users easy control over where the logging stream is directed to (file or stdout) and which level of logs to show.

**Comment by Richert** [comment]
With the latest commit, I added a couple of tests that check most of the boxes above.
The only thing we are missing at this moment is a list with known bugs/problems.
I might add that to the documentation/readme later on.
Closing this for now
