### ISSUE TITLE
Enable purely scalar network models by disabling vectorization

### ISSUE THREAD

**Issue by Richert** [pyrates-neuroscience/PyRates#23]
When calling the `CircuitIR.compile()` method, users can choose to either set `vectorization=True` or `vectorization=False`. However, currently this has no effect, since vectorization is performed in any case.

I suggest to implement the possibility to have a purely scalar network, without any vectorization being performed before the equations are parsed into the backend. This way, the compatibility with the `FortranBackend` will be improved, since it cannot handle non-scalar networks, as of now. Furthermore, this allows to create a PyAuto version of any network, since only scalar-valued differential equations are supported  by auto-07p.

**Comment by dafrose** [comment]
Makes sense. There was no reason **not** to vectorize up to now, because the other backends bundle variables into vectors one way or the other. To that effect, only the vectorized IR classes can be translated into their backend versions. This would need to be changed.

**Comment by Richert** [comment]
This feature has been implemented with the recent version update v.0.9 -> v.0.10. Using the keyword argument `vectorize`, the user can toggle between a vectorized network implementation (all nodes that have the same set of underlying equations will be grouped together) or a non-vectorized network implementation (all network equations are scalar).
