### ISSUE TITLE
Find a way to count references on structurally unique IR objects for vectorization.

### ISSUE THREAD

**Issue by dafrose** [pyrates-neuroscience/PyRates#5]
Vectorization could be sped up a lot by counting references on unique objects (like structurally identical nodes or operators). 

Can we use Python's object reference counting for this? (Might not work due to missing back links)
 
If the above is not possible, it might make sense to save these references in a database-like structure (table) for quick access. Instead we could also just save back-references of the unique objects to the places they are referenced from as a list in the respective object.

**Comment by Richert** [comment]
This would also make it easier to recognize identical operators in the backend and just define a single, compiled function for those (with only the arguments differing potentially).

**Comment by Richert** [comment]
Vectorization is now happening during the translation from templates to intermediate representations. Node and edge templates are cached and automatically extended if referred to multiple times. Thus, this can be closed
