### ISSUE TITLE
Merge ComputeGraph into CircuitIR

### ISSUE THREAD

**Issue by Richert** [pyrates-neuroscience/PyRates#6]
To improve separation between frontend and backend, I suggest to merge all `ComputeGraph` functionalities into the `CircuitIR`.

This includes:
------------------
-   vectorization of graph nodes
-   parsing of the graph nodes and edges into the backend
-   a run method for forward simulations in time

To achieve this, I suggest the following:
----------------------------------------------------
-  define a `compile` method for the  `CircuitIR` and add all arguments of the `ComputeGraph.__init__()` method to this `compile` function
-  add a `vectorize` keyword argument to the `CircuitIR.__init__()` which can be True or False for turning node vectorization of the graph on or off
-  If vectorize is True, perform vectorization on the fly while adding the nodes to the network, by comparing new nodes to the already excisting ones and vectorizing those with identical operator graph structures and names
-  To keep track of which of the original nodes resides in which vector, build a map dictionary that links the original node/op/var triplets to the respective vector indices of the new, vectorized nodes
-  Define appropriate `get_var` and `set_var` methods that allow access to variables in the network. These should work based on the above described map. Also, since we allow a hierarchical node structure, these methods should allow to reference either all nodes or a specific one at each level of that hierarchy.

**Comment by dafrose** [comment]
What should be the output of `compile`? Some kind of backend-related structure? `compile` sounds like something that should be close to the actually executed code (and function should do what it sounds like).

**Comment by Richert** [comment]
This is solved - the CircuitIR has now a `compile` method that replaces the previous `ComputeGraph.__init__()`. It takes care of the vectorization etc. Furthermore, a `get_node_var` method was added to reliably retrieve variables from the vectorized network.
